### ISSUE TITLE
typing not compatible between this and styled-components 6.0.4

### ISSUE THREAD

**Issue by michaelkay-wrisk** [The-Code-Monkey/styled-system#230]
Hi... styled-system typing is no longer compatible with newer versions of styled-components so I spiked the potential of switching over to this fork and found it has the following issue:

```
const StyledDiv = styled.div(
  css({
    backgroundColor: 'garble'
  })
)
```
With the following error:
```
TS2345: Argument of type '(props?: Theme<TLengthStyledSystem> | { theme: Theme<TLengthStyledSystem>; } | undefined) => CSSObject' is not assignable to parameter of type 'Styles<FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>'.
  Type '(props?: Theme<TLengthStyledSystem> | { theme: Theme<TLengthStyledSystem>; } | undefined) => CSSObject' is not assignable to type 'StyleFunction<FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>'.
    Type 'CSSObject' is not assignable to type 'Interpolation<object>'.
      Type 'CSSObject' is missing the following properties from type 'Interpolation<object>[]': length, pop, push, concat, and 27 more.
```
Also, I was wondering are you using this project yourself in and is your intention still to continue maintenance and development of it?

**Comment by The-Code-Monkey** [comment]
Yeah I still plan on maintaining this, currently looking for a job so not had much time, I don't personally use the CSS function, I'd be more than happy too accept a PR to fix this if you want. 

My intention to continue to develop it is because I use it in quite a few projects. I was going to attempt a fix for RSC as it doesn't work for server components out of the box currently.

**Comment by The-Code-Monkey** [comment]
Is it possible to send a screenshot of the full ts error and the implementation of the styled system CSS function so I can see the error fully

**Comment by The-Code-Monkey** [comment]
If you are having issues with CSS are there any issues with the other parsers e.g. layout, colour??

**Comment by michaelkay-wrisk** [comment]
More than happy to issue a pull request as well if you don't have the time but it won't be for a few weeks

**Comment by The-Code-Monkey** [comment]
@michaelkay-wrisk yeah exactly the reason why I continued the project id rather keep it here if that's ok, but more help is appreciated, rather than making a separate repo for the test app, branch off and then that branch can be a complete cra setup app that is used for testing. There is a test dir that I used to fix the compose, I'm assuming it's a similar issue to be honest you can find that here https://github.com/The-Code-Monkey/styled-system/tree/main/packages/styled-system/src/__test__

**Comment by The-Code-Monkey** [comment]
Hey @michaelkay-wrisk so I have found a job and start tomorrow so I will take a look at this while I'm setting the laptop up shouldn't be too hard to fix hopefully

**Comment by The-Code-Monkey** [comment]
Hi @michaelkay-wrisk i have fixed this now, its now done with an any statement, not the best solution for now but it does the job.

**Comment by The-Code-Monkey** [comment]
please close the issue after testing with the most recent version. Thanks

**Comment by The-Code-Monkey** [comment]
@michaelkay-wrisk did you ever get chance to test the latest version?

**Comment by The-Code-Monkey** [comment]
Closing due to no reply. Assuming fixed
