### ISSUE TITLE
Add `sx` prop behavior for expanding alias

### ISSUE THREAD

**Issue by Kikobeats** [The-Code-Monkey/styled-system#702]
When I write `styled-system` code using `styled-compoments`, I tend to write something like this:

```jsx
<Box css={{ pl: 0, pt: 3 }}>{children}</Box>
``` 

That's useful to group all CSS values in an object and avoid HTML pollution.

However, this doesn't work as expected, since `pl` and `pt` are shortcuts defined by styled-system.

This is the way for achieving that:

```jsx
import { css } from '@techstack/styled-system'

<Box css={css({ pl: 0, pt: 3 })}>{children}</Box>
```

Although it's now working the code looks complex. What could be really nice is to do it automagically, similar to https://theme-ui.com/sx-prop

Any idea how to achieve that? 🤔

**Comment by Kikobeats** [comment]
I found something! https://github.com/charlie-tango/emotion-sx

Could be neat implement it here

**Comment by The-Code-Monkey** [comment]
@Kikobeats you need to add this if you are getting html pollution https://styled-system-docs.vercel.app/guides/removing-props-from-html

**Comment by The-Code-Monkey** [comment]
I am also not personally a fan of the sx prop because to me thats not the styled components not the styled system way, SX to me you might as well be using css variables and inline styles on a component.

if you want to try it i believe this should work without me having to do anything https://github.com/charlie-tango/emotion-sx
